[package]
name = "lingo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defer = "0.1.0"
itertools = "0.10.3"
ncurses = "5.101.0"
rand = "0.8.5"
